import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms and conditions for using Property Insights, a Canadian real estate analysis tool.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-8 sm:py-16">
      <h1 className="text-2xl font-semibold tracking-tight mb-2">Terms of Service</h1>
      <p className="text-sm text-muted mb-10">Last updated: March 8, 2026</p>

      <div className="space-y-8 text-sm text-muted leading-relaxed">
        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Acceptance of Terms</h2>
          <p>
            By accessing or using Property Insights at propertyinsights.xyz (&quot;the Service&quot;),
            you agree to be bound by these terms. If you do not agree, please do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">What the Service Provides</h2>
          <p>
            Property Insights is a research and analysis tool for Canadian residential real estate.
            The Service provides property assessment data, offer price modeling, seller motivation
            scoring, and AI-generated analysis for informational purposes.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Not Professional Advice</h2>
          <p>
            The information provided by Property Insights is for research and educational purposes
            only. It does not constitute real estate advice, financial advice, legal advice, or an
            appraisal. Offer prices generated by our models are estimates based on publicly available
            data and should not be treated as guaranteed outcomes.
          </p>
          <p className="mt-3">
            You should always consult with a licensed real estate professional, mortgage broker, or
            lawyer before making any purchase decision or submitting an offer on a property.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Data Accuracy</h2>
          <p>
            We source data from public government assessment databases, third-party listing services,
            and AI analysis. While we work to keep information current and accurate, we cannot
            guarantee that all data is complete, up to date, or free from error.
          </p>
          <p className="mt-3">
            Assessment values are sourced from provincial authorities and may not reflect current
            market conditions. Listing data may become stale between refresh cycles. AI-generated
            narratives are produced by language models and may contain inaccuracies.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">User Accounts</h2>
          <p>
            Some features require a free account through our authentication provider (Clerk). You are
            responsible for maintaining the security of your account credentials. You agree not to
            share your account or use the Service for any unlawful purpose.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Acceptable Use</h2>
          <p className="mb-3">You agree not to:</p>
          <ul className="list-disc list-inside space-y-1.5">
            <li>Use automated tools to scrape or bulk-download data from the Service.</li>
            <li>Redistribute, resell, or sublicense data obtained from the Service.</li>
            <li>Use the Service to harass, defraud, or mislead others.</li>
            <li>Attempt to reverse-engineer the Service or its algorithms.</li>
            <li>Interfere with the Service&apos;s infrastructure or other users&apos; access.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Partner Referrals and Affiliate Relationships</h2>
          <p>
            Property Insights may offer to connect you with third-party professionals including
            mortgage brokers, real estate agents, home inspectors, and insurance providers. These
            connections are made only at your express request (by clicking a connection button and
            confirming).
          </p>
          <p className="mt-3">
            We may receive referral fees or commissions from partners when you use their services
            after being connected through Property Insights. This does not affect the analysis,
            scoring, or offer recommendations you see on the platform, which are generated
            independently by our algorithms.
          </p>
          <p className="mt-3">
            We are not responsible for the services, advice, or actions of third-party professionals.
            Any engagement with a referred professional is a separate relationship governed by their
            own terms and licensing requirements.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Behavioral Data and Consent</h2>
          <p>
            With your consent, we track how you use the Service (properties viewed, assessments
            requested, cities of interest) to improve our recommendations and to facilitate
            relevant partner connections. You control what we track and who we share it with
            through the consent preferences presented when you create an account.
          </p>
          <p className="mt-3">
            You may withdraw consent at any time without losing access to the core Service. See
            our{" "}
            <a href="/privacy" className="text-foreground hover:underline">
              Privacy Policy
            </a>{" "}
            for details on how your data is collected, stored, and shared.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Intellectual Property</h2>
          <p>
            The scoring algorithms, offer models, AI-generated narratives, and visual design of
            Property Insights are our intellectual property. You may use the analysis results for your
            own personal research and decision-making. You may not reproduce, distribute, or create
            derivative works from our content for commercial purposes without written permission.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Limitation of Liability</h2>
          <p>
            Property Insights is provided &quot;as is&quot; without warranties of any kind, either
            express or implied. We are not liable for any damages arising from your use of the
            Service, including but not limited to financial losses from real estate transactions
            informed by our analysis.
          </p>
          <p className="mt-3">
            To the maximum extent permitted by Canadian law, our total liability for any claim
            related to the Service is limited to the amount you paid us for the Service (which, for
            free accounts, is zero).
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the Service at any time, for
            any reason, with or without notice. You may stop using the Service at any time.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Governing Law</h2>
          <p>
            These terms are governed by the laws of British Columbia, Canada. Any disputes will be
            resolved in the courts of British Columbia.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Changes to These Terms</h2>
          <p>
            We may modify these terms at any time. Changes take effect when posted to this page.
            Continued use of the Service after changes are posted constitutes your acceptance of the
            revised terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-medium text-foreground mb-2">Contact</h2>
          <p>
            Questions about these terms? Reach us at{" "}
            <a
              href="mailto:hello@propertyinsights.xyz"
              className="text-foreground hover:underline"
            >
              hello@propertyinsights.xyz
            </a>.
          </p>
        </section>
      </div>
    </main>
  );
}
